services:
  kong:
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.supabase-kong.rule=Host(`db.leadingai.info`)"
      - "traefik.http.routers.supabase-kong.tls=true"
      - "traefik.http.routers.supabase-kong.tls.certresolver=letsencrypt"
      - "traefik.http.services.supabase-kong.loadbalancer.server.port=8000"
    ports: []

networks:
  traefik:
    external: true
